version: '2.4'

services:

    redis:

      networks:
        - webnet

      image: 'redis:5.0.7-alpine'
      container_name: hmi_redis
      ports:
        - 6379:6379

    app:

      networks: 
        - webnet

      image: 'romanidze/hmi_app:latest'

      build:

        target: development_build
        context: hmi_app
        dockerfile: docker/Dockerfile
        args:
          - DOCKERIZE_VERSION=v0.6.1
          - POETRY_VERSION=1.0.3
          - FLASK_ENV=production

      depends_on: 
          - redis

      container_name: hmi_app
      volumes:
        - ./hmi_app:/code
      ports:
        - 6500:6500
      command: launch-app

networks:
  webnet:
